--
-- CC1
--

CREATE TABLE "ARTISTS" (
	"ID" NUMBER, 
        "NAME" VARCHAR2(255 BYTE)
);

CREATE TABLE "CERTIFICATION" (
	"CODE" VARCHAR2(20 BYTE), 
        "DESCRIPTION" VARCHAR2(1024 BYTE)
);

CREATE TABLE "COMPANIES" (
	"ID" NUMBER, 
        "NAME" VARCHAR2(255 BYTE)
);

CREATE TABLE "COPIES" (
	"NUM_COPY" NUMBER, 
        "MOVIE" NUMBER
);

CREATE TABLE "COUNTRIES" (
	"CODE" VARCHAR2(20 BYTE), 
        "NAME" VARCHAR2(255 BYTE)
);

CREATE TABLE "GENRES" (
	"ID" NUMBER, 
        "NAME" VARCHAR2(64 BYTE)
);

CREATE TABLE "IMAGES" (
	"ID" NUMBER, 
        "IMAGE" BLOB, 
        "MOVIE" NUMBER
);

CREATE TABLE "LANGUAGES" (
	"CODE" VARCHAR2(20 BYTE), 
        "NAME" VARCHAR2(64 BYTE)
);

CREATE TABLE "LOGS" (
	"ID" VARCHAR2(20 BYTE), 
        "DATE_LOG" DATE, 
        "ERRCODE" NUMBER, 
        "MESSAGE" VARCHAR2(4000 BYTE)
);

CREATE TABLE "MOVIE_DIRECT" (
	"MOVIE" NUMBER, 
        "DIRECTOR" NUMBER
);

CREATE TABLE "MOVIE_GENRES" (
	"GENRE" NUMBER, 
        "MOVIE" NUMBER
);

CREATE TABLE "MOVIE_PLAY" (
	"MOVIE" NUMBER, 
        "ARTIST" NUMBER
);

CREATE TABLE "MOVIES" (
	"ID" NUMBER, 
        "TITLE" VARCHAR2(255 BYTE), 
        "OVERVIEW" VARCHAR2(4000 BYTE), 
        "RATING" NUMBER, 
        "RELEASED_DATE" DATE, 
        "VOTE_AVERAGE" NUMBER, 
        "VOTE_COUNT" NUMBER, 
        "CERTIFICATION" VARCHAR2(10 BYTE), 
        "PRODUCTION_COUNTRY" VARCHAR2(4 BYTE), 
        "RUNTIME" NUMBER, 
        "NB_COPIES" NUMBER
);

CREATE TABLE "PRODUCTION_COMPANIES" (
	"COMPANY" NUMBER, 
        "MOVIE" NUMBER
);

CREATE TABLE "PROJECTION" (
	"MOVIE" NUMBER, 
        "COPY" NUMBER, 
        "TIME_SLOT" NUMBER, 
        "DAY" DATE, 
        "ROOM" VARCHAR2(20 BYTE), 
        "REMAINING_SEATS" NUMBER
);

CREATE TABLE "PROJECTION_ARCHIVES" (
	"MOVIE" NUMBER, 
        "TOTAL_DAYS" NUMBER, 
        "TOTAL_SEATS" NUMBER
);

CREATE TABLE "ROOM" (
	"ID" VARCHAR2(20 BYTE), 
        "SEATS" NUMBER
);

CREATE TABLE "SPOKEN_LANG" (
	"LANGUAGES" VARCHAR2(20 BYTE), 
        "MOVIE" NUMBER
);

CREATE TABLE "TIME_SLOT" (
	"ID" NUMBER, 
        "SLOT" VARCHAR2(20 BYTE)
);



CREATE UNIQUE INDEX "ARTISTS_PK" ON "ARTISTS" ("ID");
CREATE UNIQUE INDEX "MOVIE_PLAY_PK" ON "MOVIE_PLAY" ("MOVIE", "ARTIST");
CREATE UNIQUE INDEX "LANGUAGES_UK1" ON "LANGUAGES" ("NAME");
CREATE UNIQUE INDEX "SPOKEN_LANG_PK" ON "SPOKEN_LANG" ("LANGUAGES", "MOVIE");
CREATE UNIQUE INDEX "TIME_SLOT_PK" ON "TIME_SLOT" ("ID");
CREATE UNIQUE INDEX "COUNTRIES_PK" ON "COUNTRIES" ("CODE");
CREATE UNIQUE INDEX "MOVIE_DIRECT_PK" ON "MOVIE_DIRECT" ("MOVIE", "DIRECTOR");
CREATE UNIQUE INDEX "GENRES_PK" ON "GENRES" ("ID");
CREATE UNIQUE INDEX "COUNTRIES_UK1" ON "COUNTRIES" ("NAME");
CREATE UNIQUE INDEX "PRODUCTION_COMPANIES_PK" ON "PRODUCTION_COMPANIES" ("COMPANY", "MOVIE");
CREATE UNIQUE INDEX "MOVIES_PK" ON "MOVIES" ("ID");
CREATE UNIQUE INDEX "IMAGES_PK" ON "IMAGES" ("ID");
CREATE UNIQUE INDEX "LANGUAGES_PK" ON "LANGUAGES" ("CODE");
CREATE UNIQUE INDEX "ROOM_PK" ON "ROOM" ("ID");
CREATE UNIQUE INDEX "COMPANIES_PK" ON "COMPANIES" ("ID");
CREATE UNIQUE INDEX "COPIES_PK" ON "COPIES" ("NUM_COPY", "MOVIE");
CREATE UNIQUE INDEX "MOVIE_GENRES_PK" ON "MOVIE_GENRES" ("GENRE", "MOVIE");
CREATE UNIQUE INDEX "CERTIFICATION_PK" ON "CERTIFICATION" ("CODE");
CREATE UNIQUE INDEX "LOGS_PK" ON "LOGS" ("ID");
CREATE UNIQUE INDEX "PROJECTION_PK" ON "PROJECTION" ("MOVIE", "COPY", "TIME_SLOT", "DAY", "ROOM");
CREATE UNIQUE INDEX "PROJECTION_ARCHIVES_PK" ON "PROJECTION_ARCHIVES" ("MOVIE");

CREATE INDEX "MOVIES_TITLE" ON "MOVIES" ("TITLE");
CREATE INDEX "ARTISTS_NAME" ON "ARTISTS" ("NAME");
CREATE INDEX "MOVIES_NB_COPIES" ON "MOVIES" ("NB_COPIES");
CREATE INDEX "MOVIES_COUNTRY" ON "MOVIES" ("PRODUCTION_COUNTRY");
CREATE INDEX "GENRES_GENRE" ON "GENRES" ("NAME");
CREATE INDEX "IMAGES_INDEX1" ON "IMAGES" ("MOVIE");



ALTER TABLE "COUNTRIES" MODIFY ("CODE" NOT NULL ENABLE);
ALTER TABLE "COUNTRIES" ADD CONSTRAINT "COUNTRIES_PK" PRIMARY KEY ("CODE") USING INDEX  ENABLE;
ALTER TABLE "COUNTRIES" ADD CONSTRAINT "COUNTRIES_UK1" UNIQUE ("NAME") USING INDEX  ENABLE;

ALTER TABLE "LOGS" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "LOGS" ADD CONSTRAINT "LOGS_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;

ALTER TABLE "PROJECTION" ADD CONSTRAINT "PROJECTION_PK" PRIMARY KEY ("MOVIE", "COPY", "TIME_SLOT", "DAY", "ROOM") USING INDEX  ENABLE;
ALTER TABLE "PROJECTION" MODIFY ("ROOM" NOT NULL ENABLE);
ALTER TABLE "PROJECTION" MODIFY ("DAY" NOT NULL ENABLE);
ALTER TABLE "PROJECTION" MODIFY ("TIME_SLOT" NOT NULL ENABLE);
ALTER TABLE "PROJECTION" MODIFY ("COPY" NOT NULL ENABLE);
ALTER TABLE "PROJECTION" MODIFY ("MOVIE" NOT NULL ENABLE);

ALTER TABLE "MOVIE_PLAY" MODIFY ("MOVIE" NOT NULL ENABLE);
ALTER TABLE "MOVIE_PLAY" MODIFY ("ARTIST" NOT NULL ENABLE);
ALTER TABLE "MOVIE_PLAY" ADD CONSTRAINT "MOVIE_PLAY_PK" PRIMARY KEY ("MOVIE", "ARTIST") USING INDEX  ENABLE;

ALTER TABLE "COPIES" MODIFY ("NUM_COPY" NOT NULL ENABLE);
ALTER TABLE "COPIES" MODIFY ("MOVIE" NOT NULL ENABLE);
ALTER TABLE "COPIES" ADD CONSTRAINT "COPIES_PK" PRIMARY KEY ("NUM_COPY", "MOVIE") USING INDEX  ENABLE;

ALTER TABLE "PRODUCTION_COMPANIES" MODIFY ("COMPANY" NOT NULL ENABLE);
ALTER TABLE "PRODUCTION_COMPANIES" MODIFY ("MOVIE" NOT NULL ENABLE);
ALTER TABLE "PRODUCTION_COMPANIES" ADD CONSTRAINT "PRODUCTION_COMPANIES_PK" PRIMARY KEY ("COMPANY", "MOVIE") USING INDEX  ENABLE;

ALTER TABLE "MOVIES" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "MOVIES" MODIFY ("TITLE" NOT NULL ENABLE);
ALTER TABLE "MOVIES" MODIFY ("PRODUCTION_COUNTRY" NOT NULL ENABLE);
ALTER TABLE "MOVIES" MODIFY ("VOTE_AVERAGE" NOT NULL ENABLE);
ALTER TABLE "MOVIES" MODIFY ("VOTE_COUNT" NOT NULL ENABLE);
ALTER TABLE "MOVIES" ADD CONSTRAINT "MOVIES_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
ALTER TABLE "MOVIES" MODIFY ("NB_COPIES" NOT NULL ENABLE);
ALTER TABLE "MOVIES" ADD CONSTRAINT "MOVIES_CHK1" CHECK (VOTE_AVERAGE <= 10 AND VOTE_AVERAGE >= 0) ENABLE;

ALTER TABLE "PROJECTION_ARCHIVES" ADD CONSTRAINT "PROJECTION_ARCHIVES_PK" PRIMARY KEY ("MOVIE") USING INDEX  ENABLE;
ALTER TABLE "PROJECTION_ARCHIVES" MODIFY ("MOVIE" NOT NULL ENABLE);

ALTER TABLE "LANGUAGES" MODIFY ("CODE" NOT NULL ENABLE);
ALTER TABLE "LANGUAGES" ADD CONSTRAINT "LANGUAGES_PK" PRIMARY KEY ("CODE") USING INDEX  ENABLE;
ALTER TABLE "LANGUAGES" ADD CONSTRAINT "LANGUAGES_UK1" UNIQUE ("NAME") USING INDEX  ENABLE;

ALTER TABLE "IMAGES" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "IMAGES" ADD CONSTRAINT "IMAGES_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;

ALTER TABLE "ARTISTS" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "ARTISTS" ADD CONSTRAINT "ARTISTS_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;

ALTER TABLE "CERTIFICATION" MODIFY ("CODE" NOT NULL ENABLE);
ALTER TABLE "CERTIFICATION" ADD CONSTRAINT "CERTIFICATION_PK" PRIMARY KEY ("CODE") USING INDEX  ENABLE;
ALTER TABLE "CERTIFICATION" ADD CONSTRAINT "CERTIFICATION_CODE" CHECK (CODE IN ('G', 'PG', 'PG-13', 'R', 'NC-17')) ENABLE;

ALTER TABLE "MOVIE_GENRES" MODIFY ("GENRE" NOT NULL ENABLE);
ALTER TABLE "MOVIE_GENRES" MODIFY ("MOVIE" NOT NULL ENABLE);
ALTER TABLE "MOVIE_GENRES" ADD CONSTRAINT "MOVIE_GENRES_PK" PRIMARY KEY ("GENRE", "MOVIE") USING INDEX  ENABLE;

ALTER TABLE "ROOM" ADD CONSTRAINT "ROOM_CHK1" CHECK (SEATS >= 0) ENABLE;
ALTER TABLE "ROOM" ADD CONSTRAINT "ROOM_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
ALTER TABLE "ROOM" MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE "MOVIE_DIRECT" MODIFY ("MOVIE" NOT NULL ENABLE);
ALTER TABLE "MOVIE_DIRECT" MODIFY ("DIRECTOR" NOT NULL ENABLE);
ALTER TABLE "MOVIE_DIRECT" ADD CONSTRAINT "MOVIE_DIRECT_PK" PRIMARY KEY ("MOVIE", "DIRECTOR") USING INDEX  ENABLE;

ALTER TABLE "COMPANIES" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "COMPANIES" ADD CONSTRAINT "COMPANIES_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;

ALTER TABLE "TIME_SLOT" ADD CONSTRAINT "TIME_SLOT_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
ALTER TABLE "TIME_SLOT" MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE "SPOKEN_LANG" MODIFY ("LANGUAGES" NOT NULL ENABLE);
ALTER TABLE "SPOKEN_LANG" MODIFY ("MOVIE" NOT NULL ENABLE);
ALTER TABLE "SPOKEN_LANG" ADD CONSTRAINT "SPOKEN_LANG_PK" PRIMARY KEY ("LANGUAGES", "MOVIE") USING INDEX  ENABLE;

ALTER TABLE "GENRES" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "GENRES" ADD CONSTRAINT "GENRES_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;



ALTER TABLE "COPIES" ADD CONSTRAINT "COPIES_MOVIES_FK1" FOREIGN KEY ("MOVIE")
  REFERENCES "MOVIES" ("ID") ENABLE;

ALTER TABLE "IMAGES" ADD CONSTRAINT "IMAGES_MOVIES_FK1" FOREIGN KEY ("MOVIE")
  REFERENCES "MOVIES" ("ID") ENABLE;

ALTER TABLE "MOVIE_DIRECT" ADD CONSTRAINT "MOVIE_DIRECT_ARTISTS_FK1" FOREIGN KEY ("DIRECTOR")
  REFERENCES "ARTISTS" ("ID") ENABLE;
ALTER TABLE "MOVIE_DIRECT" ADD CONSTRAINT "MOVIE_DIRECT_MOVIES_FK1" FOREIGN KEY ("MOVIE")
  REFERENCES "MOVIES" ("ID") ENABLE;

ALTER TABLE "MOVIE_GENRES" ADD CONSTRAINT "MOVIE_GENRES_GENRES_FK1" FOREIGN KEY ("GENRE")
  REFERENCES "GENRES" ("ID") ENABLE;
ALTER TABLE "MOVIE_GENRES" ADD CONSTRAINT "MOVIE_GENRES_MOVIES_FK1" FOREIGN KEY ("MOVIE")
  REFERENCES "MOVIES" ("ID") ENABLE;

ALTER TABLE "MOVIE_PLAY" ADD CONSTRAINT "MOVIE_PLAY_ARTISTS_FK1" FOREIGN KEY ("ARTIST")
  REFERENCES "ARTISTS" ("ID") ENABLE;
ALTER TABLE "MOVIE_PLAY" ADD CONSTRAINT "MOVIE_PLAY_MOVIES_FK1" FOREIGN KEY ("MOVIE")
  REFERENCES "MOVIES" ("ID") ENABLE;

ALTER TABLE "MOVIES" ADD CONSTRAINT "MOVIES_CERTIFICATION_FK1" FOREIGN KEY ("CERTIFICATION")
  REFERENCES "CERTIFICATION" ("CODE") ENABLE;

ALTER TABLE "PRODUCTION_COMPANIES" ADD CONSTRAINT "PRODUCTION_COMPANIES_COMP_FK1" FOREIGN KEY ("COMPANY")
  REFERENCES "COMPANIES" ("ID") ENABLE;
ALTER TABLE "PRODUCTION_COMPANIES" ADD CONSTRAINT "PRODUCTION_COMPANIES_MOVI_FK1" FOREIGN KEY ("MOVIE")
  REFERENCES "MOVIES" ("ID") ENABLE;

ALTER TABLE "PROJECTION" ADD CONSTRAINT "PROJECTION_COPIES_FK1" FOREIGN KEY ("COPY", "MOVIE")
  REFERENCES "COPIES" ("NUM_COPY", "MOVIE") ENABLE;
ALTER TABLE "PROJECTION" ADD CONSTRAINT "PROJECTION_ROOM_FK1" FOREIGN KEY ("ROOM")
  REFERENCES "ROOM" ("ID") ENABLE;
ALTER TABLE "PROJECTION" ADD CONSTRAINT "PROJECTION_TIME_SLOT_FK1" FOREIGN KEY ("TIME_SLOT")
  REFERENCES "TIME_SLOT" ("ID") ENABLE;

ALTER TABLE "PROJECTION_ARCHIVES" ADD CONSTRAINT "PROJECTION_ARCHIVES_MOVIE_FK1" FOREIGN KEY ("MOVIE")
  REFERENCES "MOVIES" ("ID") ENABLE;

ALTER TABLE "SPOKEN_LANG" ADD CONSTRAINT "SPOKEN_LANG_LANGUAGES_FK1" FOREIGN KEY ("LANGUAGES")
  REFERENCES "LANGUAGES" ("CODE") ENABLE;
ALTER TABLE "SPOKEN_LANG" ADD CONSTRAINT "SPOKEN_LANG_MOVIES_FK1" FOREIGN KEY ("MOVIE")
  REFERENCES "MOVIES" ("ID") ENABLE;
